drop table if exists AUTHORITY ;
drop table if exists USER ;
drop table if exists USER_AUTHORITY ;
-- drop sequence if exists authority_seq;
-- drop sequence if exists user_seq;
-- create sequence authority_seq start with 1 increment by 1;
-- create sequence user_seq start with 1 increment by 1;

CREATE TABLE AUTHORITY (
ID BIGINT NOT NULL AUTO_INCREMENT, 
NAME VARCHAR(50) NOT NULL, 
PRIMARY KEY (ID));

CREATE TABLE USER (
ID BIGINT NOT NULL AUTO_INCREMENT, 
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(150) NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL, 
LASTNAME VARCHAR(50) NOT NULL, 
EMAIL VARCHAR(150) NOT NULL,  
ENABLED BOOLEAN NOT NULL, 
LASTPASSWORDRESETDATE TIMESTAMP NOT NULL, 
PRIMARY KEY (ID));

CREATE TABLE USER_AUTHORITY (
USER_ID BIGINT NOT NULL, 
AUTHORITY_ID BIGINT NOT NULL);


ALTER TABLE USER ADD CONSTRAINT UK_SB8BBOUER5WAK8VYIIY4PF2BX UNIQUE (USERNAME);
ALTER TABLE USER_AUTHORITY ADD CONSTRAINT FKGVXJS381K6F48D5D2YI11UH89 FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY(ID);
ALTER TABLE USER_AUTHORITY ADD CONSTRAINT FKPQLSJPKYBGOS9W2SVCRI7J8XY FOREIGN KEY (USER_ID) REFERENCES USER(ID);


INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1, STR_TO_DATE('12-01-2016', '%m-%d-%Y'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1, STR_TO_DATE('04-28-2016','%m-%d-%Y'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', 0, STR_TO_DATE('01-01-2016','%m-%d-%Y'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);
COMMIT;